### ISSUE TITLE
Improve user input when the game starts

### ISSUE THREAD

**Issue by faran4engg** [NextGenDevOrg/Tauqeer-JS-Rock-Paper-Scissors-with-media-queries#1]
Its hard to type option when the game starts. 
Can we accept numbers like
1 for rock, 
2 for paper 
and 3 for scissors
And decided in our code what is chosen by the user ?

@Tanvir04khan 
@Tauqeer-Ahmed-99 
@fayez-baig 
@syedabdullahali

**Comment by Tauqeer-Ahmed-99** [comment]
I've considered this suggestion and implemented it in code, kindly review PR. @faran4engg @fayez-baig @Tanvir04khan .
